version: "2.2"
services:
  php-5.5:
    image: maadamaceno/damabox_php5.5:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/5.5:/usr/local/etc/php
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - connect

  php-5.6:
    image: maadamaceno/damabox_php5.6:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/5.6:/usr/local/etc/php
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - connect

  php-7.0:
    image: maadamaceno/damabox_php7.0:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/7.0:/usr/local/etc/php
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - connect

  php-7.1:
    image: damabox_php7.1:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/7.1:/usr/local/etc/php
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - connect

  nginx:
    image: maadamaceno/damabox_nginx:latest
    restart: always
    ports:
     - "${HTTP_PORT}:80"
    volumes:
     - ${NGINX_SERVERS_DIR}:/etc/nginx/sites-available
     - ${NGINX_LOG_DIR}:/logs
     - ${PROJECT_DIR}:/app
    networks:
      - connect

  mysql:
    image: ${MYSQL_TYPE}:${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATADIR}/${MYSQL_VERSION}:/var/lib/mysql
      - ${DB_CONFIG_DIR}/${MYSQL_TYPE}:/etc/mysql/conf.d

  firebird:
    image: maadamaceno/damabox_firebird:latest
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
      - ISC_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
    ports:
      - "${FIREBIRD_PORT}:3050"
    volumes:
      - ${FIREBIRD_DATADIR}:/databases
    networks:
      - connect

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         ip_range: 10.5.0.0/24
         gateway: 10.5.0.1
