version: "2.2"
services:
  bind:
    image: cytopia/bind:0.15
    restart: always
    hostname: bind
    dns:
      - 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "EXTRA_HOSTS=${BIND_EXTRA_HOSTS:-}"
      - "WILDCARD_DNS=${BIND_TLD_SUFFIX:-local}=127.0.0.1"
      - DNS_FORWARDER=${BIND_DNS_RESOLVER:-8.8.8.8,8.8.4.4}
    extra_hosts:
      docker.for.lin.host.internal: ${GATEWAY:-10.5.0.1}
      docker.for.lin.localhost: ${GATEWAY:-10.5.0.1}
    networks:
      connect:
        ipv4_address: ${BIND_IP:-10.5.0.10}

  php-5.5:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5.5
    restart: always
    hostname: php-5.5
    dns:
      - ${BIND_IP:-10.5.0.10}
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP55_CONFIG_DIR:-./config/php/5.5}:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - connect
    depends_on:
      - nginx

  php-5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5.6
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-5.6
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP56_CONFIG_DIR:-./config/php/5.6}:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - connect
    depends_on:
      - nginx

  php-7.0:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.1
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.0
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP70_CONFIG_DIR:-./config/php/7.0}:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - connect
    depends_on:
      - nginx

  php-7.1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.1
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.1
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP71_CONFIG_DIR:-./config/php/7.1}:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - connect
    depends_on:
      - bind
    depends_on:
      - nginx

  php-7.2:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.2
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.2
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP72_CONFIG_DIR:-./config/php/7.2}:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - connect
    depends_on:
      - nginx

  nginx:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-nginx
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: nginx
    ports:
     - "${HTTP_PORT:-80}:80"
     - "${HTTP_PORT_SSL:-443}:443"
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./config/nginx/sites-available:/etc/nginx/conf.d
     - ${PROJECT_DIR:-./data/www}:/app
    networks:
      - connect
    depends_on:
      - bind

  mysql:
    image: ${MYSQL_TYPE:-mysql}:${MYSQL_VERSION:-5.7}
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${MYSQL_DATADIR:-./data/databases/mysql}/${MYSQL_VERSION:-5.7}:/var/lib/mysql
      - ${DB_CONFIG_DIR:-./config/db}/${MYSQL_TYPE:-mysql}:/etc/mysql/conf.d
    networks:
      - connect

  firebird-2.5:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-firebird2.5
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: firebird-2.5
    ports:
      - ${FIREBIRD_PORT:-3050}:3050
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${FIREBIRD_CONFIG_FILE:-./config/db/firebird/firebird.conf}:/opt/firebird/firebird.conf
      - ${FIREBIRD_DATADIR:-./data/databases/firebird}:/databases
    networks:
      - connect
    depends_on:
      - bind

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: ${SUBNET:-10.5.0.0/24}
         ip_range: ${IP_RANGE:-10.5.0.0/24}
         gateway: ${GATEWAY:-10.5.0.1}
