version: "2.2"
services:
  php-5.5:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5.5
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP55_CONFIG_DIR:-./config/php/5.5}:/usr/local/etc/php
    networks:
      - connect

  php-5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5.6
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP56_CONFIG_DIR:-./config/php/5.6}:/usr/local/etc/php
    networks:
      - connect

  php-7.0:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.1
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP70_CONFIG_DIR:-./config/php/7.0}:/usr/local/etc/php
    networks:
      - connect

  php-7.1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.1
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP71_CONFIG_DIR:-./config/php/7.1}:/usr/local/etc/php
    networks:
      - connect

  php-7.2:
    image: maadamaceno/damabox_php7.2:latest
    restart: always
    volumes:
      - ${PROJECT_DIR:-./data/www}:/app
      - ${PHP71_CONFIG_DIR:-./config/php/7.2}:/usr/local/etc/php
    networks:
      - connect

  nginx:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
     - "${HTTP_PORT:-80}:80"
     - "${HTTP_PORT_SSL:-443}:443"
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./config/nginx/sites-available:/etc/nginx/conf.d
     - ${PROJECT_DIR:-./data/www}:/app
    networks:
      - connect

  mysql:
    image: ${MYSQL_TYPE:-mysql}:${MYSQL_VERSION:-5.7}
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ${MYSQL_DATADIR:-./data/databases/mysql}/${MYSQL_VERSION:-5.7}:/var/lib/mysql
      - ${DB_CONFIG_DIR:-./config/db}/${MYSQL_TYPE:-mysql}:/etc/mysql/conf.d
    networks:
      - connect

  firebird:
    # image: maadamaceno/damabox_hqbird:${FIREBIRD_VERSION:-2.5-sc}
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-firebird2.5
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER:-sysdba}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD:-masterkey}
    ports:
      - "${FIREBIRD_PORT:-3050}:3050"
      - "${HQBIRD_FRONT_PORT:-8082}:8082"
      - "${HQBIRD_LICENSE_PORT:-8765}:8765"
    volumes:
      - ${FIREBIRD_CONFIG_FILE:-./config/db/firebird/firebird.conf}:/opt/firebird/firebird.conf
      - ${FIREBIRD_DATADIR:-./data/databases/firebird}:/databases
    networks:
      - connect

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         ip_range: 10.5.0.0/24
         gateway: 10.5.0.1
